# Generated by Django 4.2.7 on 2025-12-01 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date_time']},
        ),
        migrations.RenameField(
            model_name='content',
            old_name='live_stream_url',
            new_name='thumbnail_url',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='content_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_datetime',
            new_name='date_time',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='end_datetime',
            new_name='end_date_time',
        ),
        migrations.RemoveField(
            model_name='content',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='content',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='content',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='content',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='content',
            name='video_file',
        ),
        migrations.RemoveField(
            model_name='event',
            name='content',
        ),
        migrations.RemoveField(
            model_name='event',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='content',
            name='duration_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='pastor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='scripture',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=10),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(choices=[('morningDew', 'The Morning Dew'), ('feastOfGlory', 'Feast of Glory'), ('wordAndPrayer', 'Word & Prayer'), ('schoolOfChrist', 'The School of Christ'), ('kingdomBusiness', 'Kingdom Business'), ('sundayService', 'Sunday Service')], max_length=50, unique=True),
        ),
    ]
