# Generated by Django 4.2.7 on 2025-11-29 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('banner_type', models.CharField(choices=[('main', 'Main Banner'), ('event', 'Event Banner'), ('announcement', 'Announcement'), ('promotion', 'Promotion')], max_length=20)),
                ('position', models.CharField(choices=[('top', 'Top'), ('middle', 'Middle'), ('bottom', 'Bottom'), ('sidebar', 'Sidebar')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('scheduled', 'Scheduled')], default='active', max_length=20)),
                ('image', models.ImageField(upload_to='banners/')),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to='banners/mobile/')),
                ('link_url', models.URLField(blank=True, null=True)),
                ('link_text', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('order', models.IntegerField(default=0, help_text='Lower numbers display first')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
