# Generated by Django 4.2.7 on 2025-12-01 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.URLField(help_text='Main banner image URL'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='mobile_image',
            field=models.URLField(blank=True, help_text='Mobile optimized image URL', null=True),
        ),
    ]
